/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a5213fef-2b55-4abb-b1bb-5a997503b483",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_9KWXGWs8l",
    "aws_user_pools_web_client_id": "7nuk74u920mlp9r7c25c1rqqq5",
    "oauth": {}
};


export default awsmobile;
